site_name: Carlos A. Estala Velasco
theme:
  name: material
  palette:
    primary: custom
    accent: cyan
  font:
    text: Montserrat
  favicon: images/favicon.ico
extra_css:
  - styles/custom.css
nav:
  - Home: index.md
  - Experience: experience.md
  - Skills: skills.md
  - Education: education.md
  - Languages: languages.md
  - Interests: interests.md